### ISSUE TITLE
undefined local variable or method `configuration' after upgrade to 0.2.0

### ISSUE THREAD

**Issue by thewatts** [rwz/ember-cli-rails#141]
Just upgraded `ember-cli-rails` to `0.2.0`, and now when starting my Rails server and hitting `http://localhost:3000`, I get this:

`undefined local variable or method 'configuration' for #<EmberCLI::App:0x007fcfe18fece8>`

Cleared out my `tmp` directory with no avail.

Unsure what could be happening. I had `0.1.*` working before upgrading to `0.2.0` - and I tried on a fresh Rails project -- it worked fine.

For some reason, on this existing project, I can't get it to work (even if I start the process over).

**Comment by rwz** [comment]
Can you provide a stacktrace?

**Comment by thewatts** [comment]
Yes indeed!

```
NameError (undefined local variable or method `configuration' for #<EmberCLI::App:0x007f81c4e5db00>):
  ember-cli-rails (0.2.0) lib/ember-cli/app.rb:89:in `method_missing'
  ember-cli-rails (0.2.0) lib/ember-cli/app.rb:117:in `block in build_timeout'
  ember-cli-rails (0.2.0) lib/ember-cli/app.rb:117:in `fetch'
  ember-cli-rails (0.2.0) lib/ember-cli/app.rb:117:in `build_timeout'
  ember-cli-rails (0.2.0) lib/ember-cli/app.rb:56:in `wait'
  ember-cli-rails (0.2.0) lib/ember-cli-rails.rb:94:in `block in each_app'
  ember-cli-rails (0.2.0) lib/ember-cli-rails.rb:94:in `each'
  ember-cli-rails (0.2.0) lib/ember-cli-rails.rb:94:in `each_app'
  ember-cli-rails (0.2.0) lib/ember-cli-rails.rb:70:in `wait!'
  ember-cli-rails (0.2.0) lib/ember-cli/middleware.rb:9:in `call'
  rack (1.6.0) lib/rack/etag.rb:24:in `call'
  rack (1.6.0) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.0) lib/rack/head.rb:13:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.0) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.0) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.1) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:649:in `call'
  activerecord (4.2.1) lib/active_record/migration.rb:378:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `_run_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_call_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.1) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.1) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.0) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.0) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.0) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/static.rb:113:in `call'
  rack (1.6.0) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.1) lib/rails/application.rb:164:in `call'
  rack (1.6.0) lib/rack/content_length.rb:15:in `call'
  thin (1.6.3) lib/thin/connection.rb:86:in `block in pre_process'
  thin (1.6.3) lib/thin/connection.rb:84:in `catch'
  thin (1.6.3) lib/thin/connection.rb:84:in `pre_process'
  thin (1.6.3) lib/thin/connection.rb:53:in `process'
  thin (1.6.3) lib/thin/connection.rb:39:in `receive_data'
  eventmachine (1.0.7) lib/eventmachine.rb:187:in `run_machine'
  eventmachine (1.0.7) lib/eventmachine.rb:187:in `run'
  thin (1.6.3) lib/thin/backends/base.rb:73:in `start'
  thin (1.6.3) lib/thin/server.rb:162:in `start'
  rack (1.6.0) lib/rack/handler/thin.rb:19:in `run'
  rack (1.6.0) lib/rack/server.rb:286:in `start'
  railties (4.2.1) lib/rails/commands/server.rb:80:in `start'
  railties (4.2.1) lib/rails/commands/commands_tasks.rb:80:in `block in server'
  railties (4.2.1) lib/rails/commands/commands_tasks.rb:75:in `tap'
  railties (4.2.1) lib/rails/commands/commands_tasks.rb:75:in `server'
  railties (4.2.1) lib/rails/commands/commands_tasks.rb:39:in `run_command!'
  railties (4.2.1) lib/rails/commands.rb:17:in `<top (required)>'
  bin/rails:4:in `require'
  bin/rails:4:in `<main>'
```

**Comment by thewatts** [comment]
Thanks for the speedy response @rwz!

**Comment by thewatts** [comment]
@rwz -> Looks like it's blowing up due to me not having a `timeout: ` setting in my app declaration in `config/initializers/ember.rb`.

Without specifying it, `options.fetch` is returning `configuration.build_timeout`
https://github.com/rwz/ember-cli-rails/blob/master/lib/ember-cli/app.rb#L117

Which, `configuration` doesn't exist in the app instance.

**Comment by rwz** [comment]
Fixed in 0.2.1 :)

**Comment by thewatts** [comment]
:) Thanks, @rwz !
